services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "2000:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 1883 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  esp32-server:
    build: ./server
    depends_on:
      mosquitto:
        condition: service_healthy
      db:
        condition: service_healthy
  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
