services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "2000:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 1883 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  esp32-server:
    build: ./server
    depends_on:
      mosquitto:
        condition: service_healthy
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esp32
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - ./db/data:/var/lib/postgresql/data
