services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "2000:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 0.0.0.0 1883 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  esp32-server:
    build: ./server
    depends_on:
      mosquitto:
        condition: service_healthy
      db:
        condition: service_healthy
  
  db:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./db/data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=deusto
      - DOCKER_INFLUXDB_INIT_BUCKET=udmt
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=udmt_super_secure_token
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
